### ISSUE TITLE
/github/workspace/example could not be found

### ISSUE THREAD

**Issue by jimmy927** [anaynayak/python-vulture-action#1]
```
running vulture example --min-confidence 90
Error: /github/workspace/example could not be found.
```

An ideas what went wrong ?

**Comment by anaynayak** [comment]
@jimmy927  I'm using the action in one of my other repositories. [Working example](https://github.com/anaynayak/buildnotify/blob/ad4b09157bde0a7f32903ec11d2a6a4c020b3375/.github/workflows/main.yml#L19). Sample [run](https://github.com/anaynayak/buildnotify/runs/1957239595?check_suite_focus=true) 

Can you share more details ? Is example a directory in the workspace ?
