### ISSUE TITLE
GitHub action should be v1.0, not v1, as shown in README file

### ISSUE THREAD

**Issue by northwestwitch** [anaynayak/python-vulture-action#2]
Thanks for the amazing software and GitHub action!

I've been struggling to make it work for a while, then I've realized that the the example provided in the README file is not exact:

The line:
```
uses: anaynayak/python-vulture-action@v1
```
Should be:
```
uses: anaynayak/python-vulture-action@v1.0
```

Hope this might help other users!

**Comment by anaynayak** [comment]
Thanks for reporting this @northwestwitch . I've pushed a fix for the same with https://github.com/anaynayak/python-vulture-action/commit/2983313ce15153d62c57fede2734896977d188ec

Feel free to raise an issue/PR for anything else you find!
